site_name: csvtk - CSV/TSV Toolkit
pages:
- Home: index.md
- Download: download.md
- Documents:
    - Usage: usage.md
    - Tutorial: tutorial.md
- More tools: bioinf.md
theme: yeti

repo_url: https://github.com/shenwei356/csvtk
site_description: csvtk - CSV/TSV toolkit
site_author: shenwei356
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/csvtk']
